### ISSUE TITLE
Admin should also be directed to set up 2fa for the monitor server

### ISSUE THREAD

**Issue by harlo** [freedomofpress/securedrop#1031]
Docs imply that this step only applies to the app server.

**Comment by ageis** [comment]
We fixed this a while ago in develop, were you looking at an older or release branch when you did the install?

**Comment by conorsch** [comment]
The test installation procedure was based on a signed release tag 0.3.3. Depending on how the docs were viewed, e.g. via a browser based off the `develop` branch or the release branch, this could have been confusing. 

Still, I think the original issue holds water, seeing as `docs/google_authenticator.md` still shows the heading **Set up Google Authenticator for the App Server**, even in `develop`.

**Comment by ageis** [comment]
Thanks, I had been looking at `docs/install.md`, but you're right. Just submitted a PR #1033
