### ISSUE TITLE
Audit remaining Rust crates

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6999]
The following is a list of Rust crates we depend on that have not been audited yet (by us or a trusted organization). This is in checklist form to help with coordinating work, but the same list can be obtained by running `cargo vet suggest`. It's sorted in order of size, so the reviews get bigger as you go down the list.

* [x] cargo vet diff rand_chacha 0.3.1 0.2.2
* [x] cargo vet inspect phf_shared 0.10.0
* [x] cargo vet inspect pyo3-macros 0.18.3
* [x] cargo vet inspect memsec 0.6.3
* [x] cargo vet diff rand_core 0.6.3 0.5.1
* [x] cargo vet inspect dirs-sys-next 0.1.2
* [x] cargo vet inspect rand_hc 0.2.0
* [x] cargo vet inspect dirs-next 2.0.0
* [x] cargo vet inspect ascii-canvas 3.0.0
* [x] cargo vet inspect memoffset 0.6.5
* [x] cargo vet inspect lalrpop-util 0.19.12
* [x] cargo vet inspect string_cache 0.8.7
* [x] cargo vet inspect digest 0.9.0
* [x] cargo vet inspect siphasher 0.3.10
* [x] cargo vet inspect crc32fast 1.3.2
* [x] cargo vet diff flate2 1.0.23 1.0.27
* [x] cargo vet inspect fixedbitset 0.4.2
* [x] cargo vet inspect getrandom 0.1.16
* [x] cargo vet inspect generic-array 0.14.6
* [x] ~cargo vet inspect getrandom 0.2.6~ cargo vet diff getrandom 0.1.16 0.2.6
* [x] cargo vet diff cc 1.0.73 1.0.83
* [x] cargo vet inspect ena 0.14.2
* [x] cargo vet inspect tiny-keccak 2.0.2
* [x] cargo vet inspect bitflags 1.3.2
* [x] cargo vet inspect xxhash-rust 0.8.7
* [x] cargo vet inspect term 0.7.0
* [x] cargo vet inspect pyo3-build-config 0.18.3
* [x] cargo vet inspect once_cell 1.12.0
* [x] cargo vet inspect ppv-lite86 0.2.16
* [x] cargo vet inspect smallvec 1.11.1
* [x] cargo vet diff libc 0.2.148 0.2.149
* [x] cargo vet inspect pyo3-macros-backend 0.18.3
* [x] cargo vet inspect typenum 1.15.0
* [x] cargo vet inspect pyo3-ffi 0.18.3
* [x] cargo vet inspect openssl-sys 0.9.93
* [x] cargo vet inspect rand 0.7.3
* [x] cargo vet inspect itertools 0.10.3
* [x] cargo vet inspect petgraph 0.6.4
* [x] cargo vet inspect chrono 0.4.31
* [x] cargo vet inspect openssl 0.10.57
* [ ] cargo vet inspect pyo3 0.18.3
* [x] cargo vet inspect lalrpop 0.19.12
* [x] cargo vet inspect diff 0.1.13

These are development dependencies:
* [x] cargo vet diff fastrand 2.0.0 2.0.1
* [x] cargo vet diff tempfile 3.4.0 3.5.0

**Comment by cfm** [comment]
I've (only just) started down the list in `6999-audits`.  I've also proposed minimal documentation in freedomofpress/securedrop-dev-docs#109.

**Comment by legoktm** [comment]
> I've (only just) started down the list in `6999-audits`. I've also proposed minimal documentation in [freedomofpress/securedrop-dev-docs#109](https://github.com/freedomofpress/securedrop-dev-docs/pull/109).

Yay! Since you already reviewed lalrpop-util, I've pulled in 7f943a7 in https://github.com/freedomofpress/securedrop/pull/7041.

**Comment by legoktm** [comment]
I pushed a new [`rust-audits`](https://github.com/freedomofpress/securedrop/tree/rust-audits) branch with a few more exemptions, feel free to push some more things to it and then we can turn it into a PR when it has more things.

We're currently using cargo vet's "safe-to-deply" and "safe-to-run" criteria, I wonder if we should add our own "not-malicious" criteria as a lower standard of review, which would essentially be "This crate does not appear to contain any malicious code" for some of the more advanced crates where we don't have the technical skills to certify the quality of the code but can verify it's not going to backdoor us.

**Comment by cfm** [comment]
On Mon, Oct 30, 2023 at 11:39:24AM -0700, Kunal Mehta wrote:
> We're currently using cargo vet's "safe-to-deply" and "safe-to-run"
> criteria, I wonder if we should add our own "not-malicious" criteria
> as a lower standard of review, which would essentially be "This crate
> does not appear to contain any malicious code" for some of the more
> advanced crates where we don't have the technical skills to certify
> the quality of the code but can verify it's not going to backdoor us.

I would support that, both for external clarity and for a lower barrier
to entry into this process.  Would you like me to draft this standard
and downgrade my existing reviews to it?

**Comment by legoktm** [comment]
That would be great :)

**Comment by cfm** [comment]
After discussing this further, @legoktm and I now propose just to downgrade our reviews to `safe-to-run`.  That way:
1. we still get a stamp, which we can document as equivalent to our Python diff-review practice and acceptable for our use;
2. our reviews are legible to the rest of the Cargo Vet community, using an existing standard; but
3. we don't overpromise `safe-to-deploy`.

**Comment by legoktm** [comment]
+1. And I'll add that for straightforward diffs where we do we feel qualified to mark it as `safe-to-deploy`, we still should. (I suspect a number of *diffs* will meet this criteria, it's just the initial review that we can't guarantee yet.)

----

I had tried to implement a `not-malicious` custom criteria (see https://github.com/freedomofpress/securedrop/commit/8b1f6496f742efc0842f4556f66f76c4cf237db7), but it's painful to add a criteria that is lower than safe-to-deploy/safe-to-run, because you can't modify that those two policies imply your custom criteria (TODO: file/find an upstream bug for this). So re-using safe-to-run, which IMO matches what we want, avoids this entire mess too.

**Comment by legoktm** [comment]
OK, I pushed the switch to `safe-to-run` to the rust-audits branch. It's functional, but it has a WIP right now since I didn't fill out a proper commit message.
